### ISSUE TITLE
checkpoint_final.pth not able to reproduce results on zero-shot CXR14

### ISSUE THREAD

**Issue by HieuPhan33** [MediaBrain-SJTU/MedKLIP#12]
Hi authors,

I have downloaded the provided checkpoint checkpoint_final.pth at https://drive.google.com/drive/folders/1HBShH7J_pO8onkzuweDgDq2QPqj6zjG_?usp=sharing.

I run test.py for zero-shot CXR classification using the provided ckpt:
`python test.py --config configs/MedKLIP_config.yaml --model_path ../PreTrain_MedKLIP/data_file/checkpoint_final.pth`

 However, the results are lower than the ones reported in the paper (f1=25.25%, acc=86.19%, auc=76.76%). 
 The results achieved from the provided `checkpoint_final.pth` are as below.

The average AUROC is 0.7233
The AUROC of atelectasis is 0.6734914678557434
The AUROC of cardiomegaly is 0.8387354032971739
The AUROC of effusion is 0.8139300050065004
The AUROC of infiltrate is 0.7074230082126723
The AUROC of mass is 0.7431034543143955
The AUROC of nodule is 0.630932431970152
The AUROC of pneumonia is 0.7065881144112844
The AUROC of pneumothorax is 0.835565412282201
The AUROC of consolidation is 0.7228670178278536
The AUROC of edema is 0.8016393905964656
The AUROC of emphysema is 0.7613106657328478
The AUROC of tail_abnorm_obs is 0.5860758325578675
The AUROC of thicken is 0.5322492353159572
The AUROC of hernia is 0.7723938628718332
The average f1 is 0.2541
The average ACC is 0.7940

I see that ACC and AUC are much lower than reported results. Could you please advise how to reproduce the results on zero-shot CXR14?

**Comment by chaoyi-wu** [comment]
The provided test.csv is the official split and in paper, we actually report the number tested on our own random split. On the official split our, the results are just around 0.72

**Comment by HieuPhan33** [comment]
Thanks for your clarification.

**Comment by JingfengYao** [comment]
Sorry to bother you again. So does it mean the results in Table 5 are also based on a random split instead of the official one? (e.g. CXR14 100% mAUC 83.23)
