### ISSUE TITLE
label中的标签问题

### ISSUE THREAD

**Issue by CCCalcifer** [MediaBrain-SJTU/MedKLIP#3]
从landmark_observation_adj_mtx.npy文件中读取的标签包含-1，0，1三种类型的值
但在model_MedKLIP.py中生成Mask时： `Mask = ((labels != -1) & (labels != 2)).squeeze() `。要加上labels!=2是为什么呢？
非常感谢！

**Comment by chaoyi-wu** [comment]
感谢您的提问，这是我的一个疏忽。labels!=2这句判断对于目前rad_graph提供的标签确实是多余的。

最早我们尝试过使用cheXbert（[https://arxiv.org/pdf/2004.09167.pdf](url)）作为NER model。在cheXbert中会用标签2代表uncertain，我们并不想对这样的抽取结果上计算损失，所以加入了这句判断。对于目前的版本，你完全可以删掉这一句判断。再次感谢您的细致观察！：）

**Comment by CCCalcifer** [comment]
好的明白了！非常感谢您的耐心解答：）
