### ISSUE TITLE
关于Sample_Zero-Shot_Grounding_RSNA中所用数据集的问题

### ISSUE THREAD

**Issue by CCCalcifer** [MediaBrain-SJTU/MedKLIP#4]
您好，今天在准备进行zero-shot-grouding实验的时候，发现RSNA2018_Dataset类中读入的csv文件中应该包含有每个样本的图像路径、类别以及bbox信息。但是我们在下载RSNA Pneumonia 后发现无论是其中的csv文件还是json文件都没有提供上述所需的所有信息。请问./configs/MedKLIP_config.yaml中的test.csv是经过数据处理后得到的吗？

**Comment by chaoyi-wu** [comment]
是的，我们follow了这个项目的处理方式( https://github.com/philip-mueller/lovt/blob/main/datasets/ )。

**Comment by CCCalcifer** [comment]
好的，非常感谢您的耐心回复！
