### ISSUE TITLE
Could you please upload your checkpoint and radgraph processed file in Google drive or other drive?

### ISSUE THREAD

**Issue by sangjoon-park** [MediaBrain-SJTU/MedKLIP#7]
The currently available pre-trained weights and necessary files are only uploaded to Baidu, which requires registration to download files. This effectively makes it inaccessible to foreigners outside of China. Moreover, Baidu is a closed cloud service that does not support English.

To expand the influence of research, would it be possible for you to upload the weights and necessary files to freely accessible drives such as Google Drive?

**Comment by chaoyi-wu** [comment]
Thanks for your advise. We have uploaded all corresponding files to [GoogleDrive](https://drive.google.com/drive/folders/1HBShH7J_pO8onkzuweDgDq2QPqj6zjG_?usp=sharing)
